:concurrency: 3
:timeout: 25
:verbose: true
:queues:
  # Queue priority:
  # https://github.com/mperham/sidekiq/wiki/Advanced-Options
  # https://mikerogers.io/2019/06/06/rails-6-sidekiq-queues
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge

:schedule:
  send_event_notification_job:
    # cron: '0 * * * * *'
    every: 30 seconds
    class: SendEventNotificationJob
